name: Matrix Cron Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetcher.outputs.matrix }}
    defaults:
      run:
        working-directory: tags
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - id: fetcher
        run: node .

  build:
    runs-on: ubuntu-latest
    needs: tags
    strategy:
      matrix: ${{fromJson(needs.tags.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Labels
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            cupcakearmy/static
            ghcr.io/${{ github.repository }}
          tags: ${{ matrix.tags }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: NGINX=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
