name: PR Build

on:
  pull_request:

jobs:
  tags:
    uses: ./.github/workflows/tags.yml

  build:
    needs: tags
    strategy:
      matrix: ${{fromJson(needs.tags.outputs.matrix)}}
    uses: ./.github/workflows/build.yml
    with:
      push: false
      nginx_version: ${{ matrix.version }}
      tags: ${{ matrix.tags }}