name: trial

on:
  workflow_dispatch:
  push:
  # push:
  #   tags:
  #     - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - tag: 1.20.2
            version: 1.20.2
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: false
          build-args: NGINX=${{ matrix.version }}
          tags: ${{ matrix.tag }}
